name: Jacobs Golf Journey
favicon: null
layout_spectrum: 0.3699266128242016
typography_spectrum: 0.7148576881736517
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.1875
  lightness: 0.25
  saturation: 0.4375
  rhythmicContrast: 0.5
purpose: []
